---
sidebar: sidebar 
permalink: scpivs44_post-migration.html 
keywords:  
summary: 백업 메타데이터를 VMware vSphere용 SnapCenter 플러그인으로 마이그레이션한 후 발생할 수 있는 문제 
---
= 마이그레이션 후
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
백업 메타데이터를 VMware vSphere용 SnapCenter 플러그인으로 마이그레이션한 후 발생할 수 있는 문제

* 마이그레이션 로그 번들
+
SnapCenter 설치 폴더의 'App_Data/MigrationLog' 디렉토리에서 마이그레이션 로그 번들을 다운로드합니다. 마이그레이션에 성공했는지 확인할 때까지 마이그레이션 로그 번들을 보관합니다.

* 대시보드의 작업 세부 정보
+
마이그레이션된 백업에 대한 정보는 VMware vSphere Web Client Recent jobs 창에 나열되지만 마이그레이션 후 백업을 수행할 때까지 자세한 정보는 대시보드에 표시되지 않습니다.

* 인증 오류
+
관리자 자격 증명을 사용하지 않으면 인증 오류가 발생할 수 있습니다.

+
link:scpivs44_manage_authentication_errors.html["인증 오류를 관리합니다"]

* 백업 이름
+
마이그레이션 전 백업 이름은 RGName '_hostname_Timestamp' 형식입니다. 예: '-nas_ds_RG_perf1server_07-05-2019_02.11.59.9338'.

+
마이그레이션 후 백업 이름은 RGName_Timestamp 형식입니다.

+
예: `-nas_vm_RG_07-07-2019_21.20.00.0609'.

* 사전 및 사후 스크립트
+
리소스 그룹에 대해 구성된 스크립트는 마이그레이션되지 않습니다. Windows 시스템용으로 작성된 스크립트는 Linux 기반 가상 어플라이언스에서 실행되지 않을 수 있으므로 스크립트의 전체 또는 일부를 다시 만들고 마이그레이션 후에 해당 스크립트를 추가해야 할 수 있습니다. 예를 들어, Windows의 파일 경로는 Linux에 존재하지 않으며, Linux에서 '.bat' 배치 파일의 호출은 작동하지 않습니다.

+
한 가지 해결 방법은 기존의 Windows 기반 스크립트를 Linux 기반 가상 어플라이언스에 놓고 스크립트가 아무런 변경 없이 작동하는지 테스트하는 것입니다. 올바르게 작동하지 않으면 스크립트의 각 Windows 기반 명령을 해당하는 Linux 호환 명령으로 교체합니다.

* 게스트 파일 복원 자격 증명
+
게스트 파일 복구 자격 증명이 마이그레이션되지 않습니다. 따라서 마이그레이션 후에 새 게스트 파일 자격 증명을 생성해야 합니다.

* 'CBR.OVERRIDE' 설정 파일
+
'SCBR.override' 구성 파일에서 설정을 사용자 지정한 경우 해당 파일을 SnapCenter VMware 플러그인 가상 어플라이언스로 이동하고 웹 클라이언트 서비스를 다시 시작해야 합니다.

* SnapCenter 애플리케이션 기반 플러그인 업그레이드
+
SnapCenter VMware 플러그인을 사용하여 다른 SnapCenter 플러그인을 지원하는 경우 해당 플러그인을 4.2 이상으로 업데이트해야 합니다.

* SnapCenter 서버를 제거합니다
+
VM 정합성 보장 또는 장애 발생 시 정합성이 보장되는 데이터 보호에 대해서만 SnapCenter를 사용하는 경우 모든 VM 백업이 SnapCenter VMware 플러그인으로 마이그레이션된 후 Windows 호스트에서 SnapCenter 서버를 제거할 수 있습니다


