---
sidebar: sidebar 
permalink: scpivs44_how_restore_operations_are_performed.html 
keywords:  
summary: 'VMFS 환경의 경우 VMware vSphere용 SnapCenter 플러그인은 Storage VMotion을 사용하여 클론 및 마운트 작업을 사용하여 복구 작업을 수행합니다. NFS 환경의 경우 플러그인은 네이티브 ONTAP SFSR(Single File SnapRestore)을 사용하여 대부분의 복구 작업에 더 높은 효율성을 제공합니다.' 
---
= 복원 작업 수행 방법
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


VMFS 환경의 경우 VMware vSphere용 SnapCenter 플러그인은 Storage VMotion을 사용하여 클론 및 마운트 작업을 사용하여 복구 작업을 수행합니다. NFS 환경의 경우 플러그인은 네이티브 ONTAP SFSR(Single File SnapRestore)을 사용하여 대부분의 복구 작업에 더 높은 효율성을 제공합니다. 다음 표에는 복원 작업이 수행되는 방법이 나와 있습니다.

|===
| 복원 작업 | NFS 환경에서 ONTAP SFSR을 사용하여 수행됩니다 | NFS 환경에서 Storage VMotion을 사용하여 클론 및 마운트를 수행합니다 | VMFS 환경에서 Storage VMotion을 사용하여 클론 및 마운트를 수행합니다 


| 운영 백업에서 VM 및 VMDK 복구 | 예 |  | 예 


| 보조 백업에서 VM 및 VMDK 복구 | 예 |  | 예 


| 삭제된 VM 및 VMDK를 운영 백업에서 복원합니다 | 예 |  | 예 


| 삭제된 VM 및 VMDK를 보조 백업에서 복원합니다 |  | 예 | 예 


| VM 정합성 보장 운영 백업에서 VM 및 VMDK 복구 | 예 |  | 예 


| VM 정합성 보장 보조 백업에서 VM 및 VMDK 복구 |  | 예 | 예 
|===
게스트 파일 복원 작업은 NFS 및 VMFS 환경 모두에서 Storage VMotion이 아닌 클론 및 마운트 작업을 사용하여 수행됩니다.


IMPORTANT: 복구 작업 중에 SCV에서 사전 복원을 호출하는 동안 "해결되지 않은 볼륨은 null임" 또는 "예외"라는 오류가 발생할 수 있습니다. 복제된 LUN을 데이터 저장소로 마운트하는 중 오류가 발생했습니다… 이 문제는 SnapCenter VMware 플러그인이 클론 재서명을 시도할 때 발생합니다. VMware 제한으로 인해 SnapCenter VMware 플러그인은 고급 ESXi 구성에서 자동 재서명 값을 제어할 수 없습니다.

오류에 대한 자세한 내용은 {link-with-bunes} [KB 문서: SCV 클론 또는 복구가 실패하고 'Host unresolved volumes is null^] 오류가 표시됩니다.
